/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './core.module';
import * as import2 from './loading-bar/loading-bar.actions';
import * as import3 from './loading-bar/loading-bar.service';
import * as import4 from './alert/alert.actions';
import * as import5 from './alert/alert.service';
import * as import6 from './storage';
import * as import7 from './profile/profile.service';
import * as import8 from './guards/auth-guard.service';
import * as import9 from './guards/super-admin-auth-guard.service';
import * as import10 from './guards/authenticated-auth-guard.service';
import * as import11 from '@angular/platform-browser/src/browser/title';
import * as import12 from './services/http-exceptions.service';
import * as import13 from './services/form-validation.service';
import * as import14 from './auth-store/logged-in.actions';
import * as import15 from './auth-token/auth-token.actions';
import * as import16 from './auth-store/auth-ready.actions';
import * as import17 from './profile/profile.actions';
import * as import18 from './auth-token/auth-token.service';
import * as import19 from './auth-http/auth-http.service';
import * as import20 from './account/account.service';
import * as import21 from './logger';
import * as import22 from './auth-token/external-auth.service';
import * as import23 from '@angular/core/src/di/injector';
import * as import24 from '@ngrx/store/src/store';
import * as import25 from '@angular/router/src/router';
import * as import26 from '@angular/http/src/http';
class CoreModuleInjector extends import0.NgModuleInjector<import1.CoreModule> {
  _CoreModule_0:import1.CoreModule;
  __LoadingBarActions_1:import2.LoadingBarActions;
  __LoadingBarService_2:import3.LoadingBarService;
  __AlertActions_3:import4.AlertActions;
  __AlertService_4:import5.AlertService;
  __StorageBackend_5:import6.LocalStorageBackend;
  __Storage_6:import6.Storage;
  __ProfileService_7:import7.ProfileService;
  __AuthGuard_8:import8.AuthGuard;
  __SuperAdminAuthGuard_9:import9.SuperAdminAuthGuard;
  __AuthenticatedAuthGuard_10:import10.AuthenticatedAuthGuard;
  __Title_11:import11.Title;
  __HttpExceptionService_12:import12.HttpExceptionService;
  __FormValidationService_13:import13.FormValidationService;
  __LoggedInActions_14:import14.LoggedInActions;
  __AuthTokenActions_15:import15.AuthTokenActions;
  __AuthReadyActions_16:import16.AuthReadyActions;
  __ProfileActions_17:import17.ProfileActions;
  __AuthTokenService_18:import18.AuthTokenService;
  __AuthHttp_19:import19.AuthHttp;
  __AccountService_20:import20.AccountService;
  __LoggingBackend_21:import21.ConsoleLoggerBackend;
  __Logger_22:import21.Logger;
  __ExternalAuthService_23:import22.ExternalAuthService;
  constructor(parent:import23.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _LoadingBarActions_1():import2.LoadingBarActions {
    if ((this.__LoadingBarActions_1 == null)) { (this.__LoadingBarActions_1 = new import2.LoadingBarActions()); }
    return this.__LoadingBarActions_1;
  }
  get _LoadingBarService_2():import3.LoadingBarService {
    if ((this.__LoadingBarService_2 == null)) { (this.__LoadingBarService_2 = new import3.LoadingBarService(this.parent.get(import24.Store),this._LoadingBarActions_1)); }
    return this.__LoadingBarService_2;
  }
  get _AlertActions_3():import4.AlertActions {
    if ((this.__AlertActions_3 == null)) { (this.__AlertActions_3 = new import4.AlertActions()); }
    return this.__AlertActions_3;
  }
  get _AlertService_4():import5.AlertService {
    if ((this.__AlertService_4 == null)) { (this.__AlertService_4 = new import5.AlertService(this.parent.get(import24.Store),this._AlertActions_3)); }
    return this.__AlertService_4;
  }
  get _StorageBackend_5():import6.LocalStorageBackend {
    if ((this.__StorageBackend_5 == null)) { (this.__StorageBackend_5 = new import6.LocalStorageBackend()); }
    return this.__StorageBackend_5;
  }
  get _Storage_6():import6.Storage {
    if ((this.__Storage_6 == null)) { (this.__Storage_6 = new import6.Storage(this._StorageBackend_5)); }
    return this.__Storage_6;
  }
  get _ProfileService_7():import7.ProfileService {
    if ((this.__ProfileService_7 == null)) { (this.__ProfileService_7 = new import7.ProfileService(this._Storage_6,this.parent.get(import24.Store))); }
    return this.__ProfileService_7;
  }
  get _AuthGuard_8():import8.AuthGuard {
    if ((this.__AuthGuard_8 == null)) { (this.__AuthGuard_8 = new import8.AuthGuard(this.parent.get(import25.Router),this._AlertService_4,this._ProfileService_7,this.parent.get(import24.Store))); }
    return this.__AuthGuard_8;
  }
  get _SuperAdminAuthGuard_9():import9.SuperAdminAuthGuard {
    if ((this.__SuperAdminAuthGuard_9 == null)) { (this.__SuperAdminAuthGuard_9 = new import9.SuperAdminAuthGuard(this._AuthGuard_8)); }
    return this.__SuperAdminAuthGuard_9;
  }
  get _AuthenticatedAuthGuard_10():import10.AuthenticatedAuthGuard {
    if ((this.__AuthenticatedAuthGuard_10 == null)) { (this.__AuthenticatedAuthGuard_10 = new import10.AuthenticatedAuthGuard(this._AuthGuard_8)); }
    return this.__AuthenticatedAuthGuard_10;
  }
  get _Title_11():import11.Title {
    if ((this.__Title_11 == null)) { (this.__Title_11 = new import11.Title()); }
    return this.__Title_11;
  }
  get _HttpExceptionService_12():import12.HttpExceptionService {
    if ((this.__HttpExceptionService_12 == null)) { (this.__HttpExceptionService_12 = new import12.HttpExceptionService()); }
    return this.__HttpExceptionService_12;
  }
  get _FormValidationService_13():import13.FormValidationService {
    if ((this.__FormValidationService_13 == null)) { (this.__FormValidationService_13 = new import13.FormValidationService()); }
    return this.__FormValidationService_13;
  }
  get _LoggedInActions_14():import14.LoggedInActions {
    if ((this.__LoggedInActions_14 == null)) { (this.__LoggedInActions_14 = new import14.LoggedInActions()); }
    return this.__LoggedInActions_14;
  }
  get _AuthTokenActions_15():import15.AuthTokenActions {
    if ((this.__AuthTokenActions_15 == null)) { (this.__AuthTokenActions_15 = new import15.AuthTokenActions()); }
    return this.__AuthTokenActions_15;
  }
  get _AuthReadyActions_16():import16.AuthReadyActions {
    if ((this.__AuthReadyActions_16 == null)) { (this.__AuthReadyActions_16 = new import16.AuthReadyActions()); }
    return this.__AuthReadyActions_16;
  }
  get _ProfileActions_17():import17.ProfileActions {
    if ((this.__ProfileActions_17 == null)) { (this.__ProfileActions_17 = new import17.ProfileActions()); }
    return this.__ProfileActions_17;
  }
  get _AuthTokenService_18():import18.AuthTokenService {
    if ((this.__AuthTokenService_18 == null)) { (this.__AuthTokenService_18 = new import18.AuthTokenService(this._Storage_6,this._LoadingBarService_2,this.parent.get(import26.Http),this._HttpExceptionService_12,this.parent.get(import24.Store),this._AlertService_4,this._LoggedInActions_14,this._AuthTokenActions_15,this._AuthReadyActions_16,this._ProfileActions_17)); }
    return this.__AuthTokenService_18;
  }
  get _AuthHttp_19():import19.AuthHttp {
    if ((this.__AuthHttp_19 == null)) { (this.__AuthHttp_19 = new import19.AuthHttp(this.parent.get(import26.Http),this.parent.get(import24.Store),this._HttpExceptionService_12,this._LoadingBarService_2)); }
    return this.__AuthHttp_19;
  }
  get _AccountService_20():import20.AccountService {
    if ((this.__AccountService_20 == null)) { (this.__AccountService_20 = new import20.AccountService(this._LoadingBarService_2,this.parent.get(import26.Http),this._HttpExceptionService_12,this._AuthHttp_19,this._AuthTokenService_18,this.parent.get(import24.Store),this._LoggedInActions_14,this._AuthTokenActions_15,this._ProfileActions_17)); }
    return this.__AccountService_20;
  }
  get _LoggingBackend_21():import21.ConsoleLoggerBackend {
    if ((this.__LoggingBackend_21 == null)) { (this.__LoggingBackend_21 = new import21.ConsoleLoggerBackend(this.parent.get(import24.Store))); }
    return this.__LoggingBackend_21;
  }
  get _Logger_22():import21.Logger {
    if ((this.__Logger_22 == null)) { (this.__Logger_22 = new import21.Logger(this._LoggingBackend_21)); }
    return this.__Logger_22;
  }
  get _ExternalAuthService_23():import22.ExternalAuthService {
    if ((this.__ExternalAuthService_23 == null)) { (this.__ExternalAuthService_23 = new import22.ExternalAuthService(this.parent.get(import26.Http),this._Logger_22,this._AccountService_20)); }
    return this.__ExternalAuthService_23;
  }
  createInternal():import1.CoreModule {
    this._CoreModule_0 = new import1.CoreModule(this.parent.get(import1.CoreModule,(null as any)));
    return this._CoreModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.CoreModule)) { return this._CoreModule_0; }
    if ((token === import2.LoadingBarActions)) { return this._LoadingBarActions_1; }
    if ((token === import3.LoadingBarService)) { return this._LoadingBarService_2; }
    if ((token === import4.AlertActions)) { return this._AlertActions_3; }
    if ((token === import5.AlertService)) { return this._AlertService_4; }
    if ((token === import6.StorageBackend)) { return this._StorageBackend_5; }
    if ((token === import6.Storage)) { return this._Storage_6; }
    if ((token === import7.ProfileService)) { return this._ProfileService_7; }
    if ((token === import8.AuthGuard)) { return this._AuthGuard_8; }
    if ((token === import9.SuperAdminAuthGuard)) { return this._SuperAdminAuthGuard_9; }
    if ((token === import10.AuthenticatedAuthGuard)) { return this._AuthenticatedAuthGuard_10; }
    if ((token === import11.Title)) { return this._Title_11; }
    if ((token === import12.HttpExceptionService)) { return this._HttpExceptionService_12; }
    if ((token === import13.FormValidationService)) { return this._FormValidationService_13; }
    if ((token === import14.LoggedInActions)) { return this._LoggedInActions_14; }
    if ((token === import15.AuthTokenActions)) { return this._AuthTokenActions_15; }
    if ((token === import16.AuthReadyActions)) { return this._AuthReadyActions_16; }
    if ((token === import17.ProfileActions)) { return this._ProfileActions_17; }
    if ((token === import18.AuthTokenService)) { return this._AuthTokenService_18; }
    if ((token === import19.AuthHttp)) { return this._AuthHttp_19; }
    if ((token === import20.AccountService)) { return this._AccountService_20; }
    if ((token === import21.LoggingBackend)) { return this._LoggingBackend_21; }
    if ((token === import21.Logger)) { return this._Logger_22; }
    if ((token === import22.ExternalAuthService)) { return this._ExternalAuthService_23; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const CoreModuleNgFactory:import0.NgModuleFactory<import1.CoreModule> = new import0.NgModuleFactory(CoreModuleInjector,import1.CoreModule);