/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.header-navigation[_ngcontent-%COMP%]{\r\n  display: flex;\r\n  justify-content: space-between;\r\n}\r\n.header-navigation__link[_ngcontent-%COMP%]{\r\n  padding: 5px;\r\n}\r\n.header-navigation__link--hover[_ngcontent-%COMP%]{\r\n  padding: 5px;\r\n  background-color: dimgrey;\r\n}\r\n\r\n.active-router-link[_ngcontent-%COMP%]{\r\n  background-color: orange;\r\n}'];