/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './navigation.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '@angular/core/src/render/api';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '../../core/profile/profile.service';
import * as import10 from '../../core/account/account.service';
import * as import11 from '@ngrx/store/src/store';
import * as import12 from './navigation.component.scss.shim';
import * as import13 from '@angular/router/src/directives/router_link';
import * as import14 from '@angular/router/src/directives/router_link_active';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/common/src/directives/ng_if';
import * as import17 from '@angular/router/src/directives/router_link.ngfactory';
import * as import18 from '../../../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import19 from '@angular/core/src/linker/query_list';
import * as import20 from '@angular/core/src/linker/view_container';
import * as import21 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import22 from '@angular/common/src/pipes/async_pipe';
import * as import23 from '@angular/router/src/router';
import * as import24 from '@angular/router/src/router_state';
import * as import25 from '@angular/common/src/location/location_strategy';
import * as import26 from '@angular/core/src/linker/element_ref';
export class Wrapper_NavigationComponent {
  /*private*/ _eventHandler:Function;
  context:import0.NavigationComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.NavigationComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
const nodeDebugInfos_NavigationComponent_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([import0.NavigationComponent],import0.NavigationComponent,{})];
var renderType_NavigationComponent_Host:import3.RenderComponentType = import4.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_NavigationComponent_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.NavigationComponent>;
  _NavigationComponent_0_3:Wrapper_NavigationComponent;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_NavigationComponent_Host0,renderType_NavigationComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_NavigationComponent_Host0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'navigation',import4.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_NavigationComponent0(this.viewUtils,this,0,this._el_0);
    this._NavigationComponent_0_3 = new Wrapper_NavigationComponent(this.injectorGet(import9.ProfileService,this.parentIndex),this.injectorGet(import10.AccountService,this.parentIndex),this.injectorGet(import11.Store,this.parentIndex));
    this.compView_0.create(this._NavigationComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._NavigationComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.NavigationComponent) && (0 === requestNodeIndex))) { return this._NavigationComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._NavigationComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const NavigationComponentNgFactory:import8.ComponentFactory<import0.NavigationComponent> = new import8.ComponentFactory<import0.NavigationComponent>('navigation',View_NavigationComponent_Host0,import0.NavigationComponent);
const styles_NavigationComponent:any[] = [import12.styles];
const nodeDebugInfos_NavigationComponent0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import13.RouterLinkWithHref,
    import14.RouterLinkActive
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import13.RouterLinkWithHref,
    import14.RouterLinkActive
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import13.RouterLinkWithHref,
    import14.RouterLinkActive
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import13.RouterLinkWithHref,
    import14.RouterLinkActive
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import13.RouterLinkWithHref,
    import14.RouterLinkActive
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import13.RouterLinkWithHref,
    import14.RouterLinkActive
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import13.RouterLinkWithHref,
    import14.RouterLinkActive
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import15.TemplateRef,
    import16.NgIf
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_NavigationComponent:import3.RenderComponentType = import4.createRenderComponentType('C:/Users/Fabian/OneDrive/AngularStarter/OAuthApi.AuthServer/App/src/app/navigation/navigation.component.html',0,import5.ViewEncapsulation.Emulated,styles_NavigationComponent,{});
export class View_NavigationComponent0 extends import1.DebugAppView<import0.NavigationComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _RouterLinkWithHref_4_3:import17.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_4_4:import18.Wrapper_RouterLinkActive;
  _query_RouterLink_4_0:import19.QueryList<any>;
  _query_RouterLinkWithHref_4_1:import19.QueryList<any>;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _RouterLinkWithHref_7_3:import17.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_7_4:import18.Wrapper_RouterLinkActive;
  _query_RouterLink_7_0:import19.QueryList<any>;
  _query_RouterLinkWithHref_7_1:import19.QueryList<any>;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _RouterLinkWithHref_10_3:import17.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_10_4:import18.Wrapper_RouterLinkActive;
  _query_RouterLink_10_0:import19.QueryList<any>;
  _query_RouterLinkWithHref_10_1:import19.QueryList<any>;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _RouterLinkWithHref_13_3:import17.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_13_4:import18.Wrapper_RouterLinkActive;
  _query_RouterLink_13_0:import19.QueryList<any>;
  _query_RouterLinkWithHref_13_1:import19.QueryList<any>;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _RouterLinkWithHref_16_3:import17.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_16_4:import18.Wrapper_RouterLinkActive;
  _query_RouterLink_16_0:import19.QueryList<any>;
  _query_RouterLinkWithHref_16_1:import19.QueryList<any>;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _RouterLinkWithHref_19_3:import17.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_19_4:import18.Wrapper_RouterLinkActive;
  _query_RouterLink_19_0:import19.QueryList<any>;
  _query_RouterLinkWithHref_19_1:import19.QueryList<any>;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _RouterLinkWithHref_22_3:import17.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_22_4:import18.Wrapper_RouterLinkActive;
  _query_RouterLink_22_0:import19.QueryList<any>;
  _query_RouterLinkWithHref_22_1:import19.QueryList<any>;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _vc_28:import20.ViewContainer;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import21.Wrapper_NgIf;
  _text_29:any;
  _text_30:any;
  _pipe_async_0:import22.AsyncPipe;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_NavigationComponent0,renderType_NavigationComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_NavigationComponent0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','header-navigation'),this.debug(0,0,0));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',this.debug(1,0,31));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','left'),this.debug(2,1,4));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',this.debug(3,1,22));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'a',new import4.InlineArray8(8,'class','header-navigation__link','mo','','routerLink','/','routerLinkActive','active-router-link'),this.debug(4,2,8));
    this._RouterLinkWithHref_4_3 = new import17.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import23.Router,this.parentIndex),this.parentView.injectorGet(import24.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import25.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_4_4 = new import18.Wrapper_RouterLinkActive(this.parentView.injectorGet(import23.Router,this.parentIndex),new import26.ElementRef(this._el_4),this.renderer);
    this._query_RouterLink_4_0 = new import19.QueryList<any>();
    this._query_RouterLinkWithHref_4_1 = new import19.QueryList<any>();
    this._text_5 = this.renderer.createText(this._el_4,'Home',this.debug(5,2,99));
    this._text_6 = this.renderer.createText(this._el_2,'\n        ',this.debug(6,2,107));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_2,'a',new import4.InlineArray8(8,'class','header-navigation__link','mo','','routerLink','/auth/login','routerLinkActive','active-router-link'),this.debug(7,3,8));
    this._RouterLinkWithHref_7_3 = new import17.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import23.Router,this.parentIndex),this.parentView.injectorGet(import24.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import25.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_7_4 = new import18.Wrapper_RouterLinkActive(this.parentView.injectorGet(import23.Router,this.parentIndex),new import26.ElementRef(this._el_7),this.renderer);
    this._query_RouterLink_7_0 = new import19.QueryList<any>();
    this._query_RouterLinkWithHref_7_1 = new import19.QueryList<any>();
    this._text_8 = this.renderer.createText(this._el_7,'Login',this.debug(8,3,109));
    this._text_9 = this.renderer.createText(this._el_2,'\n        ',this.debug(9,3,118));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_2,'a',new import4.InlineArray8(8,'class','header-navigation__link','mo','','routerLink','/auth/register','routerLinkActive','active-router-link'),this.debug(10,4,8));
    this._RouterLinkWithHref_10_3 = new import17.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import23.Router,this.parentIndex),this.parentView.injectorGet(import24.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import25.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_10_4 = new import18.Wrapper_RouterLinkActive(this.parentView.injectorGet(import23.Router,this.parentIndex),new import26.ElementRef(this._el_10),this.renderer);
    this._query_RouterLink_10_0 = new import19.QueryList<any>();
    this._query_RouterLinkWithHref_10_1 = new import19.QueryList<any>();
    this._text_11 = this.renderer.createText(this._el_10,'Register',this.debug(11,4,112));
    this._text_12 = this.renderer.createText(this._el_2,'\n        ',this.debug(12,4,124));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_2,'a',new import4.InlineArray8(8,'class','header-navigation__link','mo','','routerLink','/auth/verify','routerLinkActive','active-router-link'),this.debug(13,5,8));
    this._RouterLinkWithHref_13_3 = new import17.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import23.Router,this.parentIndex),this.parentView.injectorGet(import24.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import25.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_13_4 = new import18.Wrapper_RouterLinkActive(this.parentView.injectorGet(import23.Router,this.parentIndex),new import26.ElementRef(this._el_13),this.renderer);
    this._query_RouterLink_13_0 = new import19.QueryList<any>();
    this._query_RouterLinkWithHref_13_1 = new import19.QueryList<any>();
    this._text_14 = this.renderer.createText(this._el_13,'Verify',this.debug(14,5,110));
    this._text_15 = this.renderer.createText(this._el_2,'\n        ',this.debug(15,5,120));
    this._el_16 = import4.createRenderElement(this.renderer,this._el_2,'a',new import4.InlineArray8(8,'class','header-navigation__link','mo','','routerLink','/admin/roles','routerLinkActive','active-router-link'),this.debug(16,6,8));
    this._RouterLinkWithHref_16_3 = new import17.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import23.Router,this.parentIndex),this.parentView.injectorGet(import24.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import25.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_16_4 = new import18.Wrapper_RouterLinkActive(this.parentView.injectorGet(import23.Router,this.parentIndex),new import26.ElementRef(this._el_16),this.renderer);
    this._query_RouterLink_16_0 = new import19.QueryList<any>();
    this._query_RouterLinkWithHref_16_1 = new import19.QueryList<any>();
    this._text_17 = this.renderer.createText(this._el_16,'Roles',this.debug(17,6,110));
    this._text_18 = this.renderer.createText(this._el_2,'\n        ',this.debug(18,6,119));
    this._el_19 = import4.createRenderElement(this.renderer,this._el_2,'a',new import4.InlineArray8(8,'class','header-navigation__link','mo','','routerLink','/admin/users','routerLinkActive','active-router-link'),this.debug(19,7,8));
    this._RouterLinkWithHref_19_3 = new import17.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import23.Router,this.parentIndex),this.parentView.injectorGet(import24.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import25.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_19_4 = new import18.Wrapper_RouterLinkActive(this.parentView.injectorGet(import23.Router,this.parentIndex),new import26.ElementRef(this._el_19),this.renderer);
    this._query_RouterLink_19_0 = new import19.QueryList<any>();
    this._query_RouterLinkWithHref_19_1 = new import19.QueryList<any>();
    this._text_20 = this.renderer.createText(this._el_19,'Users',this.debug(20,7,110));
    this._text_21 = this.renderer.createText(this._el_2,'\n        ',this.debug(21,7,119));
    this._el_22 = import4.createRenderElement(this.renderer,this._el_2,'a',new import4.InlineArray8(8,'class','header-navigation__link','mo','','routerLink','/account','routerLinkActive','active-router-link'),this.debug(22,8,8));
    this._RouterLinkWithHref_22_3 = new import17.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import23.Router,this.parentIndex),this.parentView.injectorGet(import24.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import25.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_22_4 = new import18.Wrapper_RouterLinkActive(this.parentView.injectorGet(import23.Router,this.parentIndex),new import26.ElementRef(this._el_22),this.renderer);
    this._query_RouterLink_22_0 = new import19.QueryList<any>();
    this._query_RouterLinkWithHref_22_1 = new import19.QueryList<any>();
    this._text_23 = this.renderer.createText(this._el_22,'Account',this.debug(23,8,106));
    this._text_24 = this.renderer.createText(this._el_2,'\n    ',this.debug(24,8,117));
    this._text_25 = this.renderer.createText(this._el_0,'\n\n    ',this.debug(25,9,10));
    this._el_26 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','right'),this.debug(26,11,4));
    this._text_27 = this.renderer.createText(this._el_26,'\n\n        ',this.debug(27,11,23));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_26,this.debug(28,13,8));
    this._vc_28 = new import20.ViewContainer(28,26,this,this._anchor_28);
    this._TemplateRef_28_5 = new import15.TemplateRef_(this,28,this._anchor_28);
    this._NgIf_28_6 = new import21.Wrapper_NgIf(this._vc_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText(this._el_26,'\n    ',this.debug(29,16,14));
    this._text_30 = this.renderer.createText(this._el_0,'\n',this.debug(30,17,10));
    var disposable_0:Function = import4.subscribeToRenderElement(this,this._el_4,new import4.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_4));
    var disposable_1:Function = import4.subscribeToRenderElement(this,this._el_7,new import4.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_7));
    var disposable_2:Function = import4.subscribeToRenderElement(this,this._el_10,new import4.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_10));
    var disposable_3:Function = import4.subscribeToRenderElement(this,this._el_13,new import4.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_13));
    var disposable_4:Function = import4.subscribeToRenderElement(this,this._el_16,new import4.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_16));
    var disposable_5:Function = import4.subscribeToRenderElement(this,this._el_19,new import4.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_19));
    var disposable_6:Function = import4.subscribeToRenderElement(this,this._el_22,new import4.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_22));
    this.debug((null as any),(null as any),(null as any));
    this._pipe_async_0 = new import22.AsyncPipe(this.ref);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._text_30
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._RouterLinkWithHref_4_3.context; }
    if (((token === import14.RouterLinkActive) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._RouterLinkActive_4_4.context; }
    if (((token === import13.RouterLinkWithHref) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._RouterLinkWithHref_7_3.context; }
    if (((token === import14.RouterLinkActive) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._RouterLinkActive_7_4.context; }
    if (((token === import13.RouterLinkWithHref) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._RouterLinkWithHref_10_3.context; }
    if (((token === import14.RouterLinkActive) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._RouterLinkActive_10_4.context; }
    if (((token === import13.RouterLinkWithHref) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._RouterLinkWithHref_13_3.context; }
    if (((token === import14.RouterLinkActive) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._RouterLinkActive_13_4.context; }
    if (((token === import13.RouterLinkWithHref) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._RouterLinkWithHref_16_3.context; }
    if (((token === import14.RouterLinkActive) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._RouterLinkActive_16_4.context; }
    if (((token === import13.RouterLinkWithHref) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._RouterLinkWithHref_19_3.context; }
    if (((token === import14.RouterLinkActive) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._RouterLinkActive_19_4.context; }
    if (((token === import13.RouterLinkWithHref) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._RouterLinkWithHref_22_3.context; }
    if (((token === import14.RouterLinkActive) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._RouterLinkActive_22_4.context; }
    if (((token === import15.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import16.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this.debug(4,2,46);
    const currVal_4_0_0:any = '/';
    this._RouterLinkWithHref_4_3.check_routerLink(currVal_4_0_0,throwOnChange,false);
    this._RouterLinkWithHref_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this.debug(4,2,61);
    const currVal_4_1_0:any = 'active-router-link';
    this._RouterLinkActive_4_4.check_routerLinkActive(currVal_4_1_0,throwOnChange,false);
    this._RouterLinkActive_4_4.ngDoCheck(this,this._el_4,throwOnChange);
    this.debug(7,3,46);
    const currVal_7_0_0:any = '/auth/login';
    this._RouterLinkWithHref_7_3.check_routerLink(currVal_7_0_0,throwOnChange,false);
    this._RouterLinkWithHref_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    this.debug(7,3,71);
    const currVal_7_1_0:any = 'active-router-link';
    this._RouterLinkActive_7_4.check_routerLinkActive(currVal_7_1_0,throwOnChange,false);
    this._RouterLinkActive_7_4.ngDoCheck(this,this._el_7,throwOnChange);
    this.debug(10,4,46);
    const currVal_10_0_0:any = '/auth/register';
    this._RouterLinkWithHref_10_3.check_routerLink(currVal_10_0_0,throwOnChange,false);
    this._RouterLinkWithHref_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    this.debug(10,4,74);
    const currVal_10_1_0:any = 'active-router-link';
    this._RouterLinkActive_10_4.check_routerLinkActive(currVal_10_1_0,throwOnChange,false);
    this._RouterLinkActive_10_4.ngDoCheck(this,this._el_10,throwOnChange);
    this.debug(13,5,46);
    const currVal_13_0_0:any = '/auth/verify';
    this._RouterLinkWithHref_13_3.check_routerLink(currVal_13_0_0,throwOnChange,false);
    this._RouterLinkWithHref_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    this.debug(13,5,72);
    const currVal_13_1_0:any = 'active-router-link';
    this._RouterLinkActive_13_4.check_routerLinkActive(currVal_13_1_0,throwOnChange,false);
    this._RouterLinkActive_13_4.ngDoCheck(this,this._el_13,throwOnChange);
    this.debug(16,6,46);
    const currVal_16_0_0:any = '/admin/roles';
    this._RouterLinkWithHref_16_3.check_routerLink(currVal_16_0_0,throwOnChange,false);
    this._RouterLinkWithHref_16_3.ngDoCheck(this,this._el_16,throwOnChange);
    this.debug(16,6,72);
    const currVal_16_1_0:any = 'active-router-link';
    this._RouterLinkActive_16_4.check_routerLinkActive(currVal_16_1_0,throwOnChange,false);
    this._RouterLinkActive_16_4.ngDoCheck(this,this._el_16,throwOnChange);
    this.debug(19,7,46);
    const currVal_19_0_0:any = '/admin/users';
    this._RouterLinkWithHref_19_3.check_routerLink(currVal_19_0_0,throwOnChange,false);
    this._RouterLinkWithHref_19_3.ngDoCheck(this,this._el_19,throwOnChange);
    this.debug(19,7,72);
    const currVal_19_1_0:any = 'active-router-link';
    this._RouterLinkActive_19_4.check_routerLinkActive(currVal_19_1_0,throwOnChange,false);
    this._RouterLinkActive_19_4.ngDoCheck(this,this._el_19,throwOnChange);
    this.debug(22,8,46);
    const currVal_22_0_0:any = '/account';
    this._RouterLinkWithHref_22_3.check_routerLink(currVal_22_0_0,throwOnChange,false);
    this._RouterLinkWithHref_22_3.ngDoCheck(this,this._el_22,throwOnChange);
    this.debug(22,8,68);
    const currVal_22_1_0:any = 'active-router-link';
    this._RouterLinkActive_22_4.check_routerLinkActive(currVal_22_1_0,throwOnChange,false);
    this._RouterLinkActive_22_4.ngDoCheck(this,this._el_22,throwOnChange);
    this.debug(28,13,13);
    valUnwrapper.reset();
    const currVal_28_0_0:any = valUnwrapper.unwrap(this._pipe_async_0.transform(this.context.loggedIn));
    this._NgIf_28_6.check_ngIf(currVal_28_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgIf_28_6.ngDoCheck(this,this._anchor_28,throwOnChange);
    this._vc_28.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_4_0.dirty) {
        this._query_RouterLink_4_0.reset(([] as any[]));
        this._RouterLinkActive_4_4.context.links = this._query_RouterLink_4_0;
        this._query_RouterLink_4_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_4_1.dirty) {
        this._query_RouterLinkWithHref_4_1.reset([this._RouterLinkWithHref_4_3.context]);
        this._RouterLinkActive_4_4.context.linksWithHrefs = this._query_RouterLinkWithHref_4_1;
        this._query_RouterLinkWithHref_4_1.notifyOnChanges();
      }
      if (this._query_RouterLink_7_0.dirty) {
        this._query_RouterLink_7_0.reset(([] as any[]));
        this._RouterLinkActive_7_4.context.links = this._query_RouterLink_7_0;
        this._query_RouterLink_7_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_7_1.dirty) {
        this._query_RouterLinkWithHref_7_1.reset([this._RouterLinkWithHref_7_3.context]);
        this._RouterLinkActive_7_4.context.linksWithHrefs = this._query_RouterLinkWithHref_7_1;
        this._query_RouterLinkWithHref_7_1.notifyOnChanges();
      }
      if (this._query_RouterLink_10_0.dirty) {
        this._query_RouterLink_10_0.reset(([] as any[]));
        this._RouterLinkActive_10_4.context.links = this._query_RouterLink_10_0;
        this._query_RouterLink_10_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_10_1.dirty) {
        this._query_RouterLinkWithHref_10_1.reset([this._RouterLinkWithHref_10_3.context]);
        this._RouterLinkActive_10_4.context.linksWithHrefs = this._query_RouterLinkWithHref_10_1;
        this._query_RouterLinkWithHref_10_1.notifyOnChanges();
      }
      if (this._query_RouterLink_13_0.dirty) {
        this._query_RouterLink_13_0.reset(([] as any[]));
        this._RouterLinkActive_13_4.context.links = this._query_RouterLink_13_0;
        this._query_RouterLink_13_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_13_1.dirty) {
        this._query_RouterLinkWithHref_13_1.reset([this._RouterLinkWithHref_13_3.context]);
        this._RouterLinkActive_13_4.context.linksWithHrefs = this._query_RouterLinkWithHref_13_1;
        this._query_RouterLinkWithHref_13_1.notifyOnChanges();
      }
      if (this._query_RouterLink_16_0.dirty) {
        this._query_RouterLink_16_0.reset(([] as any[]));
        this._RouterLinkActive_16_4.context.links = this._query_RouterLink_16_0;
        this._query_RouterLink_16_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_16_1.dirty) {
        this._query_RouterLinkWithHref_16_1.reset([this._RouterLinkWithHref_16_3.context]);
        this._RouterLinkActive_16_4.context.linksWithHrefs = this._query_RouterLinkWithHref_16_1;
        this._query_RouterLinkWithHref_16_1.notifyOnChanges();
      }
      if (this._query_RouterLink_19_0.dirty) {
        this._query_RouterLink_19_0.reset(([] as any[]));
        this._RouterLinkActive_19_4.context.links = this._query_RouterLink_19_0;
        this._query_RouterLink_19_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_19_1.dirty) {
        this._query_RouterLinkWithHref_19_1.reset([this._RouterLinkWithHref_19_3.context]);
        this._RouterLinkActive_19_4.context.linksWithHrefs = this._query_RouterLinkWithHref_19_1;
        this._query_RouterLinkWithHref_19_1.notifyOnChanges();
      }
      if (this._query_RouterLink_22_0.dirty) {
        this._query_RouterLink_22_0.reset(([] as any[]));
        this._RouterLinkActive_22_4.context.links = this._query_RouterLink_22_0;
        this._query_RouterLink_22_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_22_1.dirty) {
        this._query_RouterLinkWithHref_22_1.reset([this._RouterLinkWithHref_22_3.context]);
        this._RouterLinkActive_22_4.context.linksWithHrefs = this._query_RouterLinkWithHref_22_1;
        this._query_RouterLinkWithHref_22_1.notifyOnChanges();
      }
      this.debug(4,2,8);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_4_4.context.ngAfterContentInit(); }
      this.debug(7,3,8);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_7_4.context.ngAfterContentInit(); }
      this.debug(10,4,8);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_10_4.context.ngAfterContentInit(); }
      this.debug(13,5,8);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_13_4.context.ngAfterContentInit(); }
      this.debug(16,6,8);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_16_4.context.ngAfterContentInit(); }
      this.debug(19,7,8);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_19_4.context.ngAfterContentInit(); }
      this.debug(22,8,8);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_22_4.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_4_3.checkHost(this,this,this._el_4,throwOnChange);
    this._RouterLinkWithHref_7_3.checkHost(this,this,this._el_7,throwOnChange);
    this._RouterLinkWithHref_10_3.checkHost(this,this,this._el_10,throwOnChange);
    this._RouterLinkWithHref_13_3.checkHost(this,this,this._el_13,throwOnChange);
    this._RouterLinkWithHref_16_3.checkHost(this,this,this._el_16,throwOnChange);
    this._RouterLinkWithHref_19_3.checkHost(this,this,this._el_19,throwOnChange);
    this._RouterLinkWithHref_22_3.checkHost(this,this,this._el_22,throwOnChange);
  }
  destroyInternal():void {
    this._vc_28.destroyNestedViews();
    this._RouterLinkWithHref_4_3.ngOnDestroy();
    this._RouterLinkActive_4_4.ngOnDestroy();
    this.debug(4,2,8);
    this._RouterLinkWithHref_7_3.ngOnDestroy();
    this._RouterLinkActive_7_4.ngOnDestroy();
    this.debug(7,3,8);
    this._RouterLinkWithHref_10_3.ngOnDestroy();
    this._RouterLinkActive_10_4.ngOnDestroy();
    this.debug(10,4,8);
    this._RouterLinkWithHref_13_3.ngOnDestroy();
    this._RouterLinkActive_13_4.ngOnDestroy();
    this.debug(13,5,8);
    this._RouterLinkWithHref_16_3.ngOnDestroy();
    this._RouterLinkActive_16_4.ngOnDestroy();
    this.debug(16,6,8);
    this._RouterLinkWithHref_19_3.ngOnDestroy();
    this._RouterLinkActive_19_4.ngOnDestroy();
    this.debug(19,7,8);
    this._RouterLinkWithHref_22_3.ngOnDestroy();
    this._RouterLinkActive_22_4.ngOnDestroy();
    this.debug(22,8,8);
    this.debug(28,13,8);
    this._pipe_async_0.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 28)) { return new View_NavigationComponent1(this.viewUtils,this,28,this._anchor_28,this._vc_28); }
    return (null as any);
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.debug(4,2,8);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_4_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.debug(7,3,8);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_7_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.debug(10,4,8);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_10_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_13(eventName:string,$event:any):boolean {
    this.debug(13,5,8);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_13_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_16(eventName:string,$event:any):boolean {
    this.debug(16,6,8);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_16_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_19(eventName:string,$event:any):boolean {
    this.debug(19,7,8);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_19_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_22(eventName:string,$event:any):boolean {
    this.debug(22,8,8);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_22_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
const nodeDebugInfos_NavigationComponent1:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import13.RouterLinkWithHref],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
class View_NavigationComponent1 extends import1.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _RouterLinkWithHref_2_3:import17.Wrapper_RouterLinkWithHref;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_6:any;
  _pipe_async_0:import22.AsyncPipe;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import20.ViewContainer) {
    super(View_NavigationComponent1,renderType_NavigationComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_NavigationComponent1,declaredViewContainer);
    this._expr_6 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',import4.EMPTY_INLINE_ARRAY,this.debug(0,13,8));
    this._text_1 = this.renderer.createText(this._el_0,'',this.debug(1,13,39));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'a',new import4.InlineArray2(2,'routerLink','/'),this.debug(2,15,12));
    this._RouterLinkWithHref_2_3 = new import17.Wrapper_RouterLinkWithHref(this.parentView.parentView.injectorGet(import23.Router,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import24.ActivatedRoute,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import25.LocationStrategy,this.parentView.parentIndex));
    this._text_3 = this.renderer.createText(this._el_2,'Logout',this.debug(3,15,57));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',this.debug(4,15,67));
    this.debug((null as any),(null as any),(null as any));
    this._pipe_async_0 = new import22.AsyncPipe(this.parentView.ref);
    var disposable_0:Function = import4.subscribeToRenderElement(this,this._el_2,new import4.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._RouterLinkWithHref_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this.debug(2,15,15);
    const currVal_2_0_0:any = '/';
    this._RouterLinkWithHref_2_3.check_routerLink(currVal_2_0_0,throwOnChange,false);
    this._RouterLinkWithHref_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this.debug(1,13,39);
    valUnwrapper.reset();
    const currVal_6:any = import4.inlineInterpolate(1,'\n            Welcome ',valUnwrapper.unwrap(this._pipe_async_0.transform(this.parentView.context.username)),'\n            ');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_6,currVal_6))) {
      this.renderer.setText(this._text_1,currVal_6);
      this._expr_6 = currVal_6;
    }
    this._RouterLinkWithHref_2_3.checkHost(this,this,this._el_2,throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_2_3.ngOnDestroy();
    this.debug(2,15,12);
    this._pipe_async_0.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.debug(2,15,12);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_2_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.account.logout()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}