/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.alert-container[_ngcontent-%COMP%]{\r\n  z-index: -1;\r\n  position: fixed;\r\n  display: flex;\r\n  flex-direction: column;\r\n  align-items: flex-end;\r\n  width: 100%;\r\n}\r\n.alert[_ngcontent-%COMP%]{\r\n  width: 300px;\r\n  text-align: center;\r\n  background-color: lightgray;\r\n  padding: 5px;\r\n}\r\n\r\n.alert-type-0[_ngcontent-%COMP%]{\r\n  background-color: green;\r\n}\r\n.alert-type-1[_ngcontent-%COMP%]{\r\n  background-color: #5eb2ff;\r\n}\r\n.alert-type-2[_ngcontent-%COMP%]{\r\n  background-color: #fdba2c;\r\n}\r\n.alert-type-3[_ngcontent-%COMP%]{\r\n  background-color: #da4733;\r\n}'];