/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.load-bar[_ngcontent-%COMP%] {\r\n  position: absolute;\r\n  width: 100%;\r\n  height: 6px;\r\n  top:0;\r\n  background-color: #fdba2c;\r\n}\r\n.bar[_ngcontent-%COMP%] {\r\n  content: "";\r\n  display: inline;\r\n  position: absolute;\r\n  width: 0;\r\n  height: 100%;\r\n  left: 50%;\r\n  text-align: center;\r\n}\r\n.bar[_ngcontent-%COMP%]:nth-child(1) {\r\n  background-color: #da4733;\r\n  animation: loading 3s linear infinite;\r\n}\r\n.bar[_ngcontent-%COMP%]:nth-child(2) {\r\n  background-color: #3b78e7;\r\n  animation: loading 3s linear 1s infinite;\r\n}\r\n.bar[_ngcontent-%COMP%]:nth-child(3) {\r\n  background-color: #fdba2c;\r\n  animation: loading 3s linear 2s infinite;\r\n}\r\n@keyframes loading {\r\n  from {left: 50%; width: 0;z-index:100;}\r\n  33.3333% {left: 0; width: 100%;z-index: 10;}\r\n  to {left: 0; width: 100%;}\r\n}'];